version: '3.3'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ec2-user/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ec2-user/caddy/site:/srv
    networks:
      - strapi

networks: 
  strapi: 
    external: true
